# -*- coding: utf-8 -*-
"""Codigo_Python_willl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158gXdXm-qnTfcIojb8e4MNlUEeemXMoZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

class Aluno:
    def __init__(self, nome, idade, matricula):
        self.nome = nome
        self.idade = idade
        self.matricula = matricula
        self.notas = []

    def adicionar_nota(self, nota):
        if 0 <= nota <= 10:
            self.notas.append(nota)
            print("Nota adicionada!")
        else:
            print("A nota deve estar entre 0 e 10.")

    def calcular_media(self):
        if len(self.notas) == 0:
            return 0
        return np.mean(self.notas)

    def situacao(self):
        media = self.calcular_media()
        if media >= 7:
            return "Aprovado"
        elif media >= 5:
            return "Recuperação"
        else:
            return "Reprovado"


class Turma:
    def __init__(self, nome):
        self.nome = nome
        self.alunos = []

    def cadastrar_aluno(self):
        print("\n========== CADASTRO ==========")
        nome = input("Nome: ")
        idade = input("Idade: ")

        if not idade.isdigit():
            print("Digite uma idade válida.")
            return

        idade = int(idade)
        matricula = input("Matrícula: ")

        if self.buscar_aluno(matricula):
            print("Essa matrícula já existe.")
            return

        aluno = Aluno(nome, idade, matricula)
        self.alunos.append(aluno)
        print("Aluno cadastrado!")

    def buscar_aluno(self, matricula):
        for aluno in self.alunos:
            if aluno.matricula == matricula:
                return aluno
        return None

    def cadastrar_notas(self):
        if len(self.alunos) == 0:
            print("Nenhum aluno cadastrado.")
            return

        matricula = input("Digite a matrícula: ")
        aluno = self.buscar_aluno(matricula)

        if aluno is None:
            print("Aluno não encontrado.")
            return

        quantidade = input("Quantas notas deseja cadastrar? ")

        if not quantidade.isdigit():
            print("Digite um número válido.")
            return

        quantidade = int(quantidade)

        if quantidade <= 0:
            print("A quantidade deve ser maior que zero.")
            return

        for i in range(quantidade):
            while True:
                try:
                    nota = float(input(f"Digite a nota {i + 1}: "))

                    if 0 <= nota <= 10:
                        aluno.adicionar_nota(nota)
                        break
                    else:
                        print("A nota deve estar entre 0 e 10.")
                except ValueError:
                    print("Digite apenas números.")


class Analise:
    def __init__(self, turma):
        self.turma = turma

    def criar_dataframe(self):
        dados = []

        for aluno in self.turma.alunos:
            dados.append({
                "Nome": aluno.nome,
                "Idade": aluno.idade,
                "Matricula": aluno.matricula,
                "Media": aluno.calcular_media(),
                "Situacao": aluno.situacao()
            })

        return pd.DataFrame(dados)

    def mostrar_tabela(self):
        df = self.criar_dataframe()

        if df.empty:
            print("Nenhum aluno cadastrado.")
            return

        print("\n========== TABELA ==========")
        print(df.to_string(index=False))

    def estatisticas(self):
        df = self.criar_dataframe()

        if df.empty:
            print("Nenhum aluno cadastrado.")
            return

        medias = df["Media"].to_numpy()

        print("\n========== ESTATÍSTICAS ==========")
        print("Quantidade de alunos:", len(medias))
        print("Média geral:", round(np.mean(medias), 2))
        print("Maior média:", round(np.max(medias), 2))
        print("Menor média:", round(np.min(medias), 2))
        print("Desvio padrão:", round(np.std(medias), 2))

        todas_notas = []

        for aluno in self.turma.alunos:
            for nota in aluno.notas:
                todas_notas.append(nota)

        if len(todas_notas) > 0:
            print("Maior nota:", np.max(todas_notas))
            print("Menor nota:", np.min(todas_notas))

    def melhor_aluno(self):
        df = self.criar_dataframe()

        if df.empty:
            print("Nenhum aluno cadastrado.")
            return

        maior = df["Media"].max()
        resultado = df[df["Media"] == maior]

        print("\n========== MELHOR ALUNO ==========")
        print(resultado.to_string(index=False))

    def aprovados(self):
        df = self.criar_dataframe()
        resultado = df[df["Situacao"] == "Aprovado"]

        print("\n========== APROVADOS ==========")

        if resultado.empty:
            print("Nenhum aluno aprovado.")
        else:
            print(resultado.to_string(index=False))

    def recuperacao(self):
        df = self.criar_dataframe()
        resultado = df[df["Situacao"] == "Recuperação"]

        print("\n========== RECUPERAÇÃO ==========")

        if resultado.empty:
            print("Nenhum aluno em recuperação.")
        else:
            print(resultado.to_string(index=False))

    def reprovados(self):
        df = self.criar_dataframe()
        resultado = df[df["Situacao"] == "Reprovado"]

        print("\n========== REPROVADOS ==========")

        if resultado.empty:
            print("Nenhum aluno reprovado.")
        else:
            print(resultado.to_string(index=False))

    def pesquisar_nome(self):
        df = self.criar_dataframe()

        if df.empty:
            print("Nenhum aluno cadastrado.")
            return

        nome = input("Digite o nome para pesquisar: ")

        resultado = df[
            df["Nome"].str.contains(nome, case=False)
        ]

        if resultado.empty:
            print("Nenhum aluno encontrado.")
        else:
            print(resultado.to_string(index=False))

    def filtros(self):
        df = self.criar_dataframe()

        if df.empty:
            print("Nenhum aluno cadastrado.")
            return

        print("\n========== FILTROS ==========")
        print("1 - Média maior ou igual a 7")
        print("2 - Média menor que 5")
        print("3 - Média entre 5 e 7")
        print("4 - Filtrar por idade")

        opcao = input("Escolha: ")

        if opcao == "1":
            resultado = df[df["Media"] >= 7]

        elif opcao == "2":
            resultado = df[df["Media"] < 5]

        elif opcao == "3":
            resultado = df[
                (df["Media"] >= 5) &
                (df["Media"] < 7)
            ]

        elif opcao == "4":
            idade = input("Digite a idade: ")

            if not idade.isdigit():
                print("Idade inválida.")
                return

            resultado = df[df["Idade"] == int(idade)]

        else:
            print("Opção inválida.")
            return

        if resultado.empty:
            print("Nenhum aluno encontrado.")
        else:
            print(resultado.to_string(index=False))

    def ordenar(self):
        df = self.criar_dataframe()

        if df.empty:
            print("Nenhum aluno cadastrado.")
            return

        resultado = df.sort_values(
            "Media",
            ascending=False
        )

        print("\n========== ORDENADO POR MÉDIA ==========")
        print(resultado.to_string(index=False))

    def salvar_csv(self):
        df = self.criar_dataframe()

        if df.empty:
            print("Nenhum dado para salvar.")
            return

        df.to_csv("alunos.csv", index=False)
        print("\nArquivo 'alunos.csv' salvo com sucesso!")


class Graficos:
    @staticmethod
    def medias(turma):
        if len(turma.alunos) == 0:
            print("Nenhum aluno cadastrado.")
            return

        nomes = []
        medias = []

        for aluno in turma.alunos:
            nomes.append(aluno.nome)
            medias.append(aluno.calcular_media())

        plt.figure()
        plt.bar(nomes, medias)
        plt.title("Média dos alunos")
        plt.xlabel("Alunos")
        plt.ylabel("Média")
        plt.ylim(0, 10)
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

    @staticmethod
    def situacao(turma):
        if len(turma.alunos) == 0:
            print("Nenhum aluno cadastrado.")
            return

        aprovados = 0
        recuperacao = 0
        reprovados = 0

        for aluno in turma.alunos:
            situacao = aluno.situacao()

            if situacao == "Aprovado":
                aprovados += 1
            elif situacao == "Recuperação":
                recuperacao += 1
            else:
                reprovados += 1

        categorias = [
            "Aprovados",
            "Recuperação",
            "Reprovados"
        ]

        valores = [
            aprovados,
            recuperacao,
            reprovados
        ]

        plt.figure()
        plt.bar(categorias, valores)
        plt.title("Situação da turma")
        plt.xlabel("Situação")
        plt.ylabel("Quantidade")
        plt.show()

    @staticmethod
    def aluno(aluno):
        if len(aluno.notas) == 0:
            print("Esse aluno não possui notas.")
            return

        numero = []

        for i in range(len(aluno.notas)):
            numero.append(i + 1)

        plt.figure()
        plt.plot(numero, aluno.notas, marker="o")
        plt.title("Notas de " + aluno.nome)
        plt.xlabel("Avaliação")
        plt.ylabel("Nota")
        plt.ylim(0, 10)
        plt.grid()
        plt.show()

    @staticmethod
    def comparacao(turma):
        if len(turma.alunos) == 0:
            print("Nenhum aluno cadastrado.")
            return

        nomes = []
        medias = []

        for aluno in turma.alunos:
            nomes.append(aluno.nome)
            medias.append(aluno.calcular_media())

        plt.figure()
        plt.plot(nomes, medias, marker="o")
        plt.title("Desempenho da turma")
        plt.xlabel("Alunos")
        plt.ylabel("Média")
        plt.ylim(0, 10)
        plt.xticks(rotation=45)
        plt.grid()
        plt.tight_layout()
        plt.show()


def menu():
    print("==========================================")
    print("       SISTEMA DE ANÁLISE ESCOLAR")
    print("==========================================")

    nome = input("Nome da turma: ")

    turma = Turma(nome)
    analise = Analise(turma)

    while True:
        print("\n==========================================")
        print("                  MENU")
        print("==========================================")
        print("1  - Cadastrar aluno")
        print("2  - Cadastrar notas")
        print("3  - Mostrar tabela")
        print("4  - Pesquisar aluno")
        print("5  - Estatísticas")
        print("6  - Melhor aluno")
        print("7  - Mostrar aprovados")
        print("8  - Mostrar recuperação")
        print("9  - Mostrar reprovados")
        print("10 - Filtros")
        print("11 - Ordenar por média")
        print("12 - Gráfico das médias")
        print("13 - Gráfico da situação")
        print("14 - Gráfico de um aluno")
        print("15 - Gráfico da turma")
        print("16 - Salvar CSV")
        print("0  - Sair")

        opcao = input("\nEscolha: ")

        if opcao == "1":
            turma.cadastrar_aluno()

        elif opcao == "2":
            turma.cadastrar_notas()

        elif opcao == "3":
            analise.mostrar_tabela()

        elif opcao == "4":
            analise.pesquisar_nome()

        elif opcao == "5":
            analise.estatisticas()

        elif opcao == "6":
            analise.melhor_aluno()

        elif opcao == "7":
            analise.aprovados()

        elif opcao == "8":
            analise.recuperacao()

        elif opcao == "9":
            analise.reprovados()

        elif opcao == "10":
            analise.filtros()

        elif opcao == "11":
            analise.ordenar()

        elif opcao == "12":
            Graficos.medias(turma)

        elif opcao == "13":
            Graficos.situacao(turma)

        elif opcao == "14":
            matricula = input("Digite a matrícula: ")
            aluno = turma.buscar_aluno(matricula)

            if aluno is not None:
                Graficos.aluno(aluno)
            else:
                print("Aluno não encontrado.")

        elif opcao == "15":
            Graficos.comparacao(turma)

        elif opcao == "16":
            analise.salvar_csv()

        elif opcao == "0":
            print("\nPrograma encerrado.")
            break

        else:
            print("\nOpção inválida.")


if __name__ == "__main__":
    menu()